title: "The Loan Phone Blog"
description: "Finance tips, home loan, car loan guides"
author: "AM"
baseurl: "/loanphone-test"
url: "https://amsumo9.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
